[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lsdo_geo"
description = "A package for geometry and state modeling/representation, parameterization, and mesh creation for MDO."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE.txt"}
keywords = ["geoemtry", "parameterization", "meshing", "representation", "modeling", "states"]
authors = [{name = "Andrew Fletcher", email = "afletcher168@gmail.com"}]
dependencies = [
    'numpy',
    #'vedo',
    'pyvista',
    'joblib',
    'pandas',
    'scipy',
    #'csdl_alpha @ git+https://github.com/LSDOlab/CSDL_alpha.git',
    #'lsdo_function_spaces @ git+https://github.com/LSDOlab/lsdo_function_spaces.git'
]
version = "0.1.0"

[project.optional-dependencies]
test = [
    'pytest',
    'pytest-cov',
]
docs = [
    'myst-nb',
    'sphinx>=7.0',
    'sphinx_rtd_theme',
    'sphinx-copybutton',
    'sphinx-autoapi>=3.0',
    'numpydoc',
    'gitpython',
    'sphinxcontrib-bibtex',
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
exclude = ["tutorials", "examples", "tests"]

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = [".conda", ".git", "build", "dist", "examples", "tutorials"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "optimization: marks long-running optimization test cases",
]